org: vtapi
app: battery-status
service: battery-status
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
  index:
    handler: handler.index
    events:
      - httpApi:
          path: /
          method: get
