org: vtapi
app: battery-status
service: battery-status
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  index:
    handler: handler.listChargers
    events:
      - httpApi:
          path: /
          method: get
  add:
    handler: handler.addCharger
    events:
      - httpApi:
          path: /add
          method: post
  edit:
    handler: handler.updateCharger
    events:
      - httpApi:
          path: /edit
          method: post
  delete:
    handler: handler.removeCharger
    events:
      - httpApi:
          path: /delete
          method: post
